DROP TABLE IF EXISTS DIASPOR CASCADE;
DROP TABLE IF EXISTS PLACES CASCADE;
DROP TABLE IF EXISTS COUNSILS CASCADE;
DROP TABLE IF EXISTS PERMISSIONS CASCADE;
DROP TABLE IF EXISTS RELATIONS CASCADE; 
DROP TABLE IF EXISTS JOBS CASCADE;
DROP TABLE IF EXISTS ROBOTS CASCADE;
DROP TABLE IF EXISTS ROBOT_TYPE CASCADE;
DROP TABLE IF EXISTS TASKS CASCADE;
DROP TABLE IF EXISTS ROBOT_TO_TASK CASCADE;
DROP TABLE IF EXISTS PERSON_TO_JOB CASCADE;
DROP TYPE IF EXISTS RELATION_TYPE CASCADE;

CREATE TABLE DIASPOR (
	PERSON_ID BIGSERIAL PRIMARY KEY,
	PERSON_NAME text NOT NULL,
	PERSON_BIRTH_DATE DATE NOT NULL,
	PERSON_STRENGTH integer
	CHECK(PERSON_STRENGTH >= 0)
);

CREATE TABLE ROBOT_TYPE (
	ROBOT_TYPE_NAME text PRIMARY KEY,
	ROBOT_TYPE_DESCRIPTION text
);

CREATE TABLE PLACES (
	PLACE_ID BIGSERIAL PRIMARY KEY,
	PLACE_TITLE text,
	PLACE_DESCRIPTION text,
	PLACE_X integer NOT NULL,
	PLACE_Y INTEGER NOT NULL
	CHECK(PLACE_TITLE IS NOT NULL)
);

CREATE TABLE ROBOTS (
	ROBOT_ID BIGSERIAL PRIMARY KEY,
	ROBOT_TITLE text NOT NULL,
	ROBOT_TYPE_NAME text REFERENCES ROBOT_TYPE,
	ROBOT_WORKING_PLACE BIGSERIAL REFERENCES PLACES,
	ROBOT_CREATION_DATE DATE DEFAULT CURRENT_DATE,
	ROBOTS_MAX_POWER integer DEFAULT 1, 
	CHECK(ROBOTS_MAX_POWER >= 0)
);


CREATE TABLE COUNSILS (
	COUNSIL_ID BIGSERIAL PRIMARY KEY REFERENCES DIASPOR,
	COUNSIL_RANK integer NOT NULL DEFAULT 1,
	COUNSIL_NAME text,
	JOINED_DATE DATE DEFAULT CURRENT_DATE,
	CHECK(COUNSIL_RANK > 0)
);

CREATE TABLE PERMISSIONS (
	PERMISSION_ID BIGSERIAL PRIMARY KEY,
	PERSON_ID BIGSERIAL NOT NULL REFERENCES DIASPOR,
	PLACE_ID BIGSERIAL NOT NULL REFERENCES PLACES
);

CREATE OR REPLACE FUNCTION CHECK_IS_IN_RADIUS()
RETURNS TRIGGER AS $$
DECLARE
	ALPHA numeric;
	DISTANCE numeric;
	R numeric := 20;
	CENTER_X NUMERIC;
	CENTER_Y NUMERIC;
	MIN_DIST NUMERIC := -1;
	cnt integer;
	X numeric;
	Y numeric;
BEGIN
	SELECT COUNT(*) into cnt FROM PLACES;
	IF cnt = 0 THEN
	RETURN NEW;
	END IF;
	FOR X, Y IN 
		SELECT PLACE_X AS X, PLACE_Y AS Y 
		FROM PLACES
		WHERE PLACES.PLACE_ID != NEW.PLACE_ID
	LOOP
		IF (NEW.PLACE_X - X)^2 + (NEW.PLACE_Y - Y)^2 <= R^2 THEN
			RETURN NEW;
		ELSE 
			IF (MIN_DIST = -1) OR (NEW.PLACE_X - X)^2 + (NEW.PLACE_Y - Y)^2 < MIN_DIST THEN
				MIN_DIST = (NEW.PLACE_X - X)^2 + (NEW.PLACE_Y - Y)^2;
				CENTER_X = X;
				CENTER_Y = Y;
			END IF;
		END IF;
	END LOOP;

	ALPHA := random() * 360;
	DISTANCE := random() * R;
	NEW.PLACE_X := DISTANCE * cosd(ALPHA) + CENTER_X;
	NEW.PLACE_Y := DISTANCE * sind(ALPHA) + CENTER_Y;
	RETURN NEW; 
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER TRGR_FOR_PLACES
BEFORE INSERT OR UPDATE ON PLACES
FOR EACH ROW
EXECUTE FUNCTION CHECK_IS_IN_RADIUS();

CREATE TABLE JOBS (
	JOB_ID BIGSERIAL PRIMARY KEY,
	JOB_NAME text NOT NULL DEFAULT 'UNEMPLOYED', 
	JOB_DESCRIPTION text,
	JOB_SALARY integer NOT NULL DEFAULT 0
	check(JOB_SALARY >= 0)
);

CREATE TABLE PERSON_TO_JOB (
	VACANCY_ID BIGSERIAL PRIMARY KEY,
	PERSON_ID BIGSERIAL NOT NULL REFERENCES DIASPOR,
	JOB_ID BIGSERIAL NOT NULL REFERENCES JOBS,
	PERSONS_JOB_NAME text
);

CREATE TABLE TASKS (
	TASK_ID BIGSERIAL PRIMARY KEY,
	TASK_NAME text NOT NULL,
	TASK_DESCRIPTION text,
	POWER_CONSUMPTION integer NOT NULL DEFAULT 1
	CHECK(POWER_CONSUMPTION > 0)
);

CREATE TABLE ROBOT_TO_TASK (
	CUR_TASK_ID BIGSERIAL PRIMARY KEY,
	ROBOT_ID BIGSERIAL NOT NULL REFERENCES ROBOTS,
	TASK_ID BIGSERIAL NOT NULL REFERENCES TASKS
);

INSERT INTO DIASPOR(PERSON_NAME, PERSON_BIRTH_DATE) VALUES
('person1', '2025-02-23'),
('person2', '2020-01-30'),
('person3', '2010-01-30');

INSERT INTO PLACES(PLACE_TITLE, PLACE_X, PLACE_Y) VALUES
('Counsil hall', 0, 0),
('Street ABVGD', 10, 0),
('Main palace', 10, 10), 
('Central computer hall', 25, 0),
('TOWER', 35, 0),
('FARM', 65, 0);


INSERT INTO PERMISSIONS(PERSON_ID, PLACE_ID) VALUES
(1, 1),
(2, 2), 
(3, 3),
(1, 2),
(1, 3);

INSERT INTO COUNSILS(COUNSIL_ID, COUNSIL_RANK, JOINED_DATE) VALUES
(1, 1, '2026-02-23'),
(2, 2, '2020-01-30');


UPDATE COUNSILS C
SET COUNSIL_NAME = D.PERSON_NAME
FROM DIASPOR D
WHERE C.COUNSIL_ID = D.PERSON_ID;

INSERT INTO JOBS (JOB_NAME, JOB_SALARY) VALUES
('Unemployed', 1),
('Professor', 52),
('Gamer', 322),
('Student', 13),
('Doctor', 3),
('Programmer', 27);

INSERT INTO PERSON_TO_JOB (PERSON_ID, JOB_ID) VALUES
(1, 3),
(2, 3),
(1, 2);

INSERT INTO ROBOT_TYPE (ROBOT_TYPE_NAME) VALUES
('BUYMAX'),
('MEGATHRON'),
('VALLEY'),
('CHILL GUY');

INSERT INTO ROBOTS (ROBOT_ID, ROBOT_TITLE, ROBOT_TYPE_NAME) VALUES
(1, 'абобус', 'VALLEY'),
(2, 'ROBOT2', 'MEGATHRON');

INSERT INTO ROBOTS (ROBOT_ID, ROBOT_TITLE) VALUES
(3, 'ROBOT3');

INSERT INTO TASKS (TASK_ID, TASK_NAME) VALUES
(1, 'SAFETY CHECK'),
(2, 'FUEL RENEW'),
(3, 'PRESS KACHAT');

INSERT INTO ROBOT_TO_TASK(ROBOT_ID, TASK_ID) VALUES
(1, 1),
(1, 2),
(2, 3);

INSERT INTO PERSON_TO_JOB (PERSON_ID)
SELECT PERSON_ID
FROM DIASPOR D
WHERE NOT EXISTS (
	SELECT 1 FROM PERSON_TO_JOB P2J
	WHERE D.PERSON_ID = P2J.PERSON_ID
);

UPDATE PERSON_TO_JOB
SET PERSONS_JOB_NAME = J.JOB_NAME
FROM JOBS J
WHERE PERSON_TO_JOB.JOB_ID = J.JOB_ID;

SELECT * FROM DIASPOR;
SELECT PERSON_NAME,
CASE 
WHEN date_part('year', age(CURRENT_DATE, PERSON_BIRTH_DATE)) >= 3 THEN 0
ELSE (date_part('year', age(CURRENT_DATE, PERSON_BIRTH_DATE)) - 3) * -1
END AS DIFF
FROM DIASPOR;

SELECT * FROM PLACES;