DROP TABLE IF EXISTS DIASPOR CASCADE;
DROP TABLE IF EXISTS PLACES CASCADE;
DROP TABLE IF EXISTS COUNSILS CASCADE;
DROP TABLE IF EXISTS PERMISSIONS CASCADE;
DROP TABLE IF EXISTS RELATIONS CASCADE; 
DROP TABLE IF EXISTS JOBS CASCADE;
DROP TABLE IF EXISTS ROBOTS CASCADE;
DROP TABLE IF EXISTS ROBOT_TYPE CASCADE;
DROP TABLE IF EXISTS TASKS CASCADE;
DROP TABLE IF EXISTS ROBOT_TO_TASK CASCADE;
DROP TABLE IF EXISTS PERSON_TO_JOB CASCADE;
DROP TYPE IF EXISTS RELATION_TYPE CASCADE;

CREATE TABLE DIASPOR (
	PERSON_ID BIGSERIAL PRIMARY KEY,
	PERSON_NAME text NOT NULL,
	PERSON_AGE integer NOT NULL,
	PERSON_STRENGTH integer
	CHECK(PERSON_AGE > 0 AND PERSON_STRENGTH >= 0)
);

CREATE TABLE ROBOT_TYPE (
	ROBOT_TYPE_NAME text PRIMARY KEY,
	ROBOT_TYPE_DESCRIPTION text
);

CREATE TABLE ROBOTS (
	ROBOT_ID BIGSERIAL PRIMARY KEY,
	ROBOT_TITLE text NOT NULL,
	ROBOT_TYPE_NAME text REFERENCES ROBOT_TYPE,
	ROBOT_WORKING_PLACE BIGSERIAL REFERENCES PLACES,
	ROBOT_CREATION_DATE DATE DEFAULT CURRENT_DATE,
	ROBOTS_MAX_POWER integer DEFAULT 1
	CHECK(ROBOTS_MAX_POWER >= 0)
);



CREATE TABLE PLACES (
	PLACE_ID BIGSERIAL PRIMARY KEY,
	PLACE_TITLE text,
	PLACE_DESCRIPTION text
	CHECK(PLACE_TITLE IS NOT NULL)
);

CREATE TABLE COUNSILS (
	COUNSIL_ID BIGSERIAL PRIMARY KEY REFERENCES DIASPOR,
	COUNSIL_RANK integer NOT NULL DEFAULT 1,
	COUNSIL_NAME text,
	JOINED_DATE DATE DEFAULT CURRENT_DATE,
	CHECK(COUNSIL_RANK > 0)
);

CREATE TABLE PERMISSIONS (
	PERMISSION_ID BIGSERIAL PRIMARY KEY,
	PERSON_ID BIGSERIAL NOT NULL REFERENCES DIASPOR,
	PLACE_ID BIGSERIAL NOT NULL REFERENCES PLACES
);

CREATE TABLE JOBS (
	JOB_ID BIGSERIAL PRIMARY KEY,
	JOB_NAME text NOT NULL DEFAULT 'UNEMPLOYED', 
	JOB_DESCRIPTION text,
	JOB_SALARY integer NOT NULL DEFAULT 0
	check(JOB_SALARY >= 0)
);

CREATE TABLE PERSON_TO_JOB (
	VACANCY_ID BIGSERIAL PRIMARY KEY,
	PERSON_ID BIGSERIAL NOT NULL REFERENCES DIASPOR,
	JOB_ID BIGSERIAL NOT NULL REFERENCES JOBS,
	PERSONS_JOB_NAME text
);

CREATE TABLE TASKS (
	TASK_ID BIGSERIAL PRIMARY KEY,
	TASK_NAME text NOT NULL,
	TASK_DESCRIPTION text,
	POWER_CONSUMPTION integer NOT NULL DEFAULT 1
	CHECK(POWER_CONSUMPTION > 0)
);

CREATE TABLE ROBOT_TO_TASK (
	CUR_TASK_ID BIGSERIAL PRIMARY KEY,
	ROBOT_ID BIGSERIAL NOT NULL REFERENCES ROBOTS,
	TASK_ID BIGSERIAL NOT NULL REFERENCES TASKS
);

INSERT INTO DIASPOR(PERSON_NAME, PERSON_AGE) VALUES
('person1', 1),
('person2', 2),
('person3', 52);

INSERT INTO PLACES(PLACE_TITLE) VALUES
('Counsil hall'),
('Street'),
('Main palace'), 
('Central computer hall');

INSERT INTO PERMISSIONS(PERSON_ID, PLACE_ID) VALUES
(1, 1),
(2, 2), 
(3, 3),
(1, 2),
(1, 3);

INSERT INTO COUNSILS(COUNSIL_ID, COUNSIL_RANK, JOINED_DATE) VALUES
(1, 1, '2026-02-23'),
(2, 2, '2020-01-30');


UPDATE COUNSILS C
SET COUNSIL_NAME = D.PERSON_NAME
FROM DIASPOR D
WHERE C.COUNSIL_ID = D.PERSON_ID;

INSERT INTO JOBS (JOB_NAME, JOB_SALARY) VALUES
('Unemployed', 1),
('Professor', 52),
('Gamer', 322),
('Student', 13),
('Doctor', 3),
('Programmer', 27);

INSERT INTO PERSON_TO_JOB (PERSON_ID, JOB_ID) VALUES
(1, 3),
(2, 3),
(1, 2);

INSERT INTO ROBOT_TYPE (ROBOT_TYPE_NAME) VALUES
('BUYMAX'),
('MEGATHRON'),
('VALLEY'),
('CHILL GUY');

INSERT INTO ROBOTS (ROBOT_ID, ROBOT_TITLE, ROBOT_TYPE_NAME) VALUES
(1, 'ROBOT1', 'VALLEY'),
(2, 'ROBOT2', 'MEGATHRON');

INSERT INTO ROBOTS (ROBOT_ID, ROBOT_TITLE) VALUES
(3, 'ROBOT3');

INSERT INTO TASKS (TASK_ID, TASK_NAME) VALUES
(1, 'SAFETY CHECK'),
(2, 'FUEL RENEW'),
(3, 'PRESS KACHAT');

INSERT INTO ROBOT_TO_TASK(ROBOT_ID, TASK_ID) VALUES
(1, 1),
(1, 2),
(2, 3);

INSERT INTO PERSON_TO_JOB (PERSON_ID)
SELECT PERSON_ID
FROM DIASPOR D
WHERE NOT EXISTS (
	SELECT 1 FROM PERSON_TO_JOB P2J
	WHERE D.PERSON_ID = P2J.PERSON_ID
);

UPDATE PERSON_TO_JOB
SET PERSONS_JOB_NAME = J.JOB_NAME
FROM JOBS J
WHERE PERSON_TO_JOB.JOB_ID = J.JOB_ID;

SELECT * FROM DIASPOR;
SELECT * FROM COUNSILS;
SELECT * FROM PLACES;
SELECT * FROM PERMISSIONS;
SELECT * FROM PERSON_TO_JOB;
SELECT * FROM ROBOTS;
SELECT * FROM ROBOT_TO_TASK;